services:
  caddy-proxy:
    image: lucaslorentz/caddy-docker-proxy:2.9-alpine
    container_name: caddy-proxy
    hostname: .web.oops
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=net-edge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - net-edge

volumes:
  caddy_data:
  caddy_config:

networks:
  net-edge:
    name: net-edge
    driver: bridge
