# ==============================================================================
# Oops Default Stack (compose.yml)
# ==============================================================================
# This is the default entrypoint when running `oops up` with no arguments.
# You can define which stacks should boot by declaring them in x-oops-depends_on.
# ==============================================================================

x-oops-depends_on:
  - /edge
  - /db
  - /apps

services: {}
